apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "csi-hyperstack.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csi-hyperstack.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "csi-hyperstack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "csi-hyperstack.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.hyperstack.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.hyperstack.imagePullSecret }}
      {{- end }}
      serviceAccountName: csi-hyperstack-controller-sa
      containers:
        - name: csi-hyperstack
          image: reg.digitalocean.ngbackend.cloud/hyperstack-csi-driver/csi:v0.0.1
          imagePullPolicy:  {{ .Values.components.csiHyperstack.imagePullPolicy }}
          command: ["csi-hyperstack"]
          args:
            - "start"
            - "--endpoint=unix:///csi/csi.sock"
            - "--hyperstack-api-address={{ .Values.hyperstack.apiAddress }}"
            - "--hyperstack-api-key={{ .Values.hyperstack.apiKey }}"
            - "--service-controller-enabled"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: HYPERSTACK_API_ADDRESS
              value: {{ .Values.hyperstack.apiAddress }}
            - name: HYPERSTACK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "csi-hyperstack.fullname" . }}-secrets
                  key: apiKey
            - name: HYPERSTACK_CLUSTER_ID
              value: "{{ .Values.hyperstack.clusterId }}"
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 8080
              name: auth
              protocol: TCP
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - mountPath: /var/lib/kubelet/plugins
              mountPropagation: Bidirectional
              name: plugins-dir
        {{- if .Values.components.csiAttacher.enabled }}
        - name: csi-attacher
          image: {{ .Values.components.csiAttacher.image }}
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        {{- end }}
        {{- if .Values.components.csiProvisioner.enabled }}
        - name: csi-provisioner
          image: {{ .Values.components.csiProvisioner.image }}
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
            - --feature-gates=Topology=true
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        {{- end }}
        {{- if .Values.components.csiResizer.enabled }}
        - name: csi-resizer
          image: {{ .Values.components.csiResizer.image }}
          args:
            - -v=5
            - -csi-address=/csi/csi.sock
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        {{- end }}
        {{- if .Values.components.csiSnapshotter.enabled }}
        - name: csi-snapshotter
          image: {{ .Values.components.csiSnapshotter.image }}
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        {{- end }}
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/hyperstack.csi.nexgencloud.com
            type: DirectoryOrCreate
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
        - name: plugins-dir
          hostPath:
            path: /var/lib/kubelet/plugins
            type: Directory
